---
- name: Configure EC2 instances
  hosts: all
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present
